#!/bin/sh
set -e
  GIT_OPTS=""
  OUTPUT_FILTER="cat" # no-op
  RED=$(tput setaf 1)
  GREEN=$(tput setaf 2)
  date_format=$(tput bold; tput setaf 4)
  ref_name_format=$(tput setaf 3)
  bold=$(tput bold)
  reset=$(tput sgr0)
  ifs=$IFS

# List all todos
show()
{
  IFS=""
  echo "$GREEN@done$reset"
  git notes show \
  | grep @todo \
  | sed -e 's/@todo//' \
  | while read -a task; do
    echo "$GREEN X$reset ${task}"
  done

  echo "$RED@todo$reset"
  git notes show \
  | grep @done \
  | sed -e 's/@done//' \
  | while read -a task; do
    echo "$RED O$reset ${task}"
  done
}

# Create a new Todo
add()
{
  echo $@
}

# Get rid of a todo
remove()
{
  echo $@
}

# Commit a todo as finished
finish() {
  # Commit with todo as message
  # Copy notes from HEAD~1 to HEAD
  # move message from @todo to @done
  echo $@
}

help()
{
  echo "usage: git todo show";
  echo "   or: git todo add";
  echo "   or: git todo remove";
  echo "   or: git todo finish";
}

# list
IFS=$ifs
case $1 in
  'show')
    show;;
  'add')
    add;;
  'remove')
    remove;;
  'finish')
    finish;;
  'help')
    help;;
  *)
    echo "error: unknown subcommand: $1"
    help;;
esac
